version: "3.8"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nice2strangers-frontend
    ports:
      - "5173:80" # open at http://localhost:5173
    restart: unless-stopped
