version: "3.8"

services:
  react-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nice2strangers-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
