name: Deploy to VPS Server

on:
  push:
    branches:
      - main   # change if you deploy from a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to VPS over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            if [ ! -d "/srv/nice2strangers-frontend/.git" ]; then
              git clone https://github.com/jcrocker-cmd/nice2strangers_FE.git /srv/nice2strangers-frontend
            else
              cd /srv/nice2strangers-frontend
              git pull origin main-prod
            fi
            cd /srv/nice2strangers-frontend
            docker compose down
            docker compose up -d --build
